### PR TITLE
Install used dependencies

### PR DESCRIPTION
**Pull request by szepeviktor**
On the way to pass Level max.

### CODE REVIEW

**Comment by szepeviktor** [comment]
@betterthanclay Please consider passing Level max + `phpstan/phpstan-strict-rules`.
After all this is a PHPStan extension 💎💎💎

**Comment by szepeviktor** [comment]
I see, those two packages do not support PHP 8 :(

**Comment by betterthanclay** [comment]
Hi Viktor - that's what I'm trying to work through today.

I'll come back to this pull request a bit later, though some of the things you've removed above need to be there due to concurrent issues with PHPStan's handling of call signatures.

**Comment by szepeviktor** [comment]
> some of the things you've removed above need to be ther

https://travis-ci.com/github/decodelabs/phpstan-decodelabs/jobs/491955191#L497 ✔️ 

How could tests pass then?

**Comment by szepeviktor** [comment]
All green 🍏🍏🍏🍏

**Comment by betterthanclay** [comment]
Hi Viktor, thanks for this.
I was getting a PHPStan error on those ignored lines only last night so it's either been patched in a new PHPStan release today or there's a problem with the caching mechanism (which is definitely possible). 

Good to see it's working now though - I'll get this merged in the morning 👍

**Pull request merged**
